require('_cfg.options')
require('_cfg.netrw')
require('_cfg.keymaps')
require('_cfg.autocmds')

require('_cfg.lsp')
require('_cfg.tstools')
require('_cfg.hover')
require('_cfg.lsp-virtual')
require('_cfg.cmp')
require('_cfg.telescope')
require('_cfg.treesitter')
require('_cfg.lint')
require('_cfg.conform')
require('_cfg.mini')
require('_cfg.qf')
require('_cfg.git')
require('_cfg.theme')
