require('nvim-treesitter.configs').setup({
  parser_install_dir = '~/.local/share/nvim/site',
  ensure_installed = {
    'astro',
    'bash',
    'css',
    'comment',
    'csv',
    'diff',
    'gitcommit',
    'go',
    'javascript',
    'jsdoc',
    'json',
    'jsonc',
    'html',
    'http',
    'lua',
    'markdown',
    'markdown_inline',
    'nix',
    'regex',
    'rust',
    'scss',
    'toml',
    'tsx',
    'typescript',
    'vim',
    'vimdoc',
    'yaml',
    'twig',
    'c_sharp',
    'sql',
  },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  yati = {
    enable = true,
    default_fallback = 'auto',
    suppress_conflict_warning = true,
  },
  indent = {
    enable = true,
    disable = { 'javascript', 'typescript', 'html', 'rust', 'lua', 'css', 'tsx', 'json', 'toml' },
  },
})
